name: JsonParser google test

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: beszedics/google-test
    steps:
      - name: Install google test dependecies
        run: cd /usr/src/gtest && cmake . && make && ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - uses: actions/checkout@v2
      - name: cmake
        run: cd google_test && cmake .
      - name: make build environment
        run: cd google_test && make
      - name: run google_test
        run: make unittest