name: Test workflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install cppcheck
      - run: sudo apt-get install valgrind
      - run: cppcheck *.cpp --enable=warning
      - run: g++ -std=c++17 *.cpp -Wall -Wextra -g -fsanitize=address
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python run_test.py