name: Test workflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: beszedics/test
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck *.cpp --enable=all --output-file=artifact_cppcheck.txt
      - name: Upload cppcheck as artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact_cppcheck
          path: ./artifact_cppcheck.txt
      - run: g++-9 -std=c++17 *.cpp -Wall -Wextra -g -lstdc++fs
      - uses: actions/setup-python@v2
      - run: python run_cppcheck_test.py
      - run: python run_test.py
