name: Test workflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python run_test.py
